### ISSUE TITLE
Upload File: Not clear that user must scroll to reach next steps

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/spoonbill-web#94]
The progress bar is also not visible when the user clicks Submit, unless they scroll further down.

@sabahfromlondon What do you think a good solution is? Should the page auto-scroll after clicking Submit?

https://user-images.githubusercontent.com/26463/114888858-99df2680-9dd7-11eb-9af8-238562de5771.mov

**Comment by sorenabell** [comment]
Current solution: add scroll down after analysis is finished.

**Comment by sabahfromlondon** [comment]
I just watched the video again and I think this could be a messy UX issue. I think there are two possible options:

1. Once the file has been analysed, remove the upload box and replace it with the feedback message (instead of the message being on the top right of the screen. Below that add a heading with the text: "Select how to access the flattened data"
2. The other option is for the user to be taken to a new page after the file has been analysed. The new page will have the heading "Select how to access the flattened data" and the two options only.

I think the second option will be the best one, but happy to hear other views.
